# Generated by Django 4.0.6 on 2022-07-23 02:43

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('body', django_quill.fields.QuillField()),
                ('summary', models.CharField(max_length=250, verbose_name='summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='company name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='logo')),
                ('intro_title', models.CharField(blank=True, max_length=50, verbose_name='intro title')),
                ('intro_description', models.TextField(blank=True, verbose_name='intro description')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('google_podcast', models.URLField(blank=True, verbose_name='google podcast')),
                ('apple_podcast', models.URLField(blank=True, verbose_name='apple podcast')),
                ('spotify_podcast', models.URLField(blank=True, verbose_name='spotify podcast')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('body', django_quill.fields.QuillField()),
                ('published_link', models.URLField(verbose_name='published link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'podcast',
                'verbose_name_plural': 'podcasts',
            },
        ),
        migrations.CreateModel(
            name='PodcastFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.podcast', verbose_name='podcast feature')),
            ],
            options={
                'verbose_name': 'podcast feature',
                'verbose_name_plural': 'podcast features',
            },
        ),
    ]
