# Generated by Django 4.0.6 on 2022-08-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('body_html', models.TextField(blank=True, verbose_name='rich text')),
                ('body', models.TextField(blank=True, verbose_name='plain text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('body_html', models.TextField(blank=True, verbose_name='rich text')),
                ('body', models.TextField(blank=True, verbose_name='plain text')),
                ('published_link', models.URLField(blank=True, verbose_name='published link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'podcast',
                'verbose_name_plural': 'podcasts',
                'ordering': ('-modified_at',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='company name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='logo')),
                ('podcast_title', models.CharField(blank=True, max_length=250, verbose_name='podcast title')),
                ('google_podcast', models.URLField(blank=True, verbose_name='google podcast')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('about_html', models.TextField(blank=True, default='', verbose_name='about html')),
                ('apple_podcast', models.URLField(blank=True, verbose_name='apple podcast')),
                ('spotify_podcast', models.URLField(blank=True, verbose_name='spotify podcast')),
                ('intro_title', models.CharField(blank=True, max_length=50, verbose_name='intro title')),
                ('intro_description', models.TextField(blank=True, verbose_name='intro description')),
                ('intro_description_html', models.TextField(blank=True, default='', verbose_name='intro description html')),
                ('featured_podcast', models.ManyToManyField(blank=True, to='core.podcast')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
    ]
