# Generated by Django 4.0.6 on 2022-07-23 07:55

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_body_podcast_body_quill_remove_blog_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=django_quill.fields.QuillField(blank=True, verbose_name='quill text'),
        ),
    ]
