# Generated by Django 4.0.6 on 2022-07-27 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_user_alter_podcast_body_quill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body_plain',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body_rich',
            new_name='body_html',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='body_plain',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='body_rich',
            new_name='body_html',
        ),
    ]
