# Generated by Django 4.0.6 on 2022-07-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_body_plain_blog_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_html',
            field=models.TextField(blank=True, default='', verbose_name='about html'),
        ),
        migrations.AddField(
            model_name='company',
            name='intro_description_html',
            field=models.TextField(blank=True, default='', verbose_name='intro description html'),
        ),
    ]
