# Generated by Django 4.0.6 on 2022-07-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_company_about_html_company_intro_description_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='featured_podcast',
            field=models.ManyToManyField(to='core.podcast'),
        ),
    ]
