# Generated by Django 4.0.6 on 2022-07-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_company_featured_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body_quill',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='body_quill',
        ),
    ]
