# Generated by Django 4.0.6 on 2022-07-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_company_user_alter_company_featured_podcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-modified_at',), 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ('-modified_at',), 'verbose_name': 'podcast', 'verbose_name_plural': 'podcasts'},
        ),
        migrations.AddField(
            model_name='company',
            name='podcast_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='podcast title'),
        ),
        migrations.AlterField(
            model_name='company',
            name='featured_podcast',
            field=models.ManyToManyField(blank=True, to='core.podcast'),
        ),
    ]
