# Generated by Django 4.0.6 on 2022-07-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_blog_options_alter_podcast_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PodcastFeature',
        ),
    ]
