# Generated by Django 4.0.6 on 2022-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_podcastfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='is published'),
        ),
    ]
